/** @type {import('cz-git').UserConfig} */
module.exports = {
  useEmoji: true,
  emojiAlign: 'center',
  maxSubjectLength: 100,
  maxHeaderLength: 100,
  allowEmptyScopes: true,
  allowCustomScopes: true,
  defaultScope: '',
  types: [
    { value: 'feat', name: 'feat:        ✨ 新功能', emoji: ':sparkles:' },
    { value: 'fix', name: 'fix:         🐛 问题修复', emoji: ':bug:' },
    { value: 'docs', name: 'docs:        📝 文档', emoji: ':memo:' },
    { value: 'style', name: 'style:       🎨 样式 / 格式', emoji: ':art:' },
    { value: 'refactor', name: 'refactor:    ♻️ 重构', emoji: ':recycle:' },
    { value: 'perf', name: 'perf:        🚀 性能', emoji: ':zap:' },
    { value: 'test', name: 'test:        ✅ 测试', emoji: ':white_check_mark:' },
    { value: 'build', name: 'build:       🔨 构建', emoji: ':hammer:' },
    { value: 'ci', name: 'ci:          🔧 CI', emoji: ':wrench:' },
    { value: 'chore', name: 'chore:       📦 杂项', emoji: ':package:' },
    { value: 'revert', name: 'revert:      ⏪ 回滚', emoji: ':rewind:' },
  ],
  messages: {
    type: '选择提交类型：',
    scope: '影响范围（可选，回车跳过）：',
    customScope: '自定义范围：',
    subject: '简短描述（会自动带上类型对应的表情）：',
    body: '详细说明（可选，可用 | 换行）：',
    breaking: '不兼容变更说明（可选）：',
    footerPrefixesSelect: '关联 Issue 前缀（可选）：',
    customFooterPrefix: '自定义前缀：',
    footer: '关联 Issue，如 #12、#34（可选）：',
    confirmCommit: '确认提交？',
  },
}
