export const tableStrings = {
  extension: {
    selectCell: 'Select Cell',
    selectRow: 'Select Row',
    addRow: 'Add Row',
    addRowAfter: 'Add Row After',
    addRowBefore: 'Add Row Before',
    deleteRow: 'Delete Row',
    selectColumn: 'Select Column',
    addColumn: 'Add Column',
    addColumnAfter: 'Add Column After',
    addColumnBefore: 'Add Column Before',
    deleteColumn: 'Delete Column',
  },
  menu: {
    headerColumn: 'Header Column',
    addColumnAfter: 'Add Column After',
    addColumnBefore: 'Add Column Before',
    moveColumnLeft: 'Move Column Left',
    moveColumnRight: 'Move Column Right',
    deleteColumn: 'Delete This Column',
    headerRow: 'Header Row',
    addRowAfter: 'Add Row After',
    addRowBefore: 'Add Row Before',
    moveRowUp: 'Move Row Up',
    moveRowDown: 'Move Row Down',
    deleteRow: 'Delete This Row',
  },
}
